config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "home/about" => 'homes#about'
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create, :destroy]
      get 'date_search', to: 'users#date_search'
  end

  get 'search' => 'searches#search'
  get 'category_search' => 'books#category_search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @book = Book.new
    @groups = Group.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = current_user
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    if @group.owner_id == current_user.id
      render 'edit'
    else
      redirect_to groups_path
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:motice] = "You have updated group successfully."
      redirect_to groups_path
    else
      render :edit
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to groups_path
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @title = params[:title]
    @content = params[:content]
    EventMailer.send_mail(group_users, @title, @content).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image )
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Group</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with model: @group, local:true do |f| %>
        <div class="form-group">
          <label>グループ名</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>紹介文</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>グループ画像</label>
          <%= f.attachment_field :image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Group", class: 'btn btn-success'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
          <tr>
            <td><%= attachment_image_tag group, :image, :fill, 40, 40, fallback: "no_image_icon.jpg" %></td>
            <td><%= link_to group.name, group_path(group) %></td>
            <td><%= group.introduction %></td>
            <td><%= group.users.count %></td>
            <% if current_user.id == group.owner_id %>
                <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Create Group</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with model: @group, local:true do |f| %>
        <div class="form-group">
          <label>グループ名</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>紹介文</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>グループ画像</label>
          <%= f.attachment_field :image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Group", class: 'btn btn-success'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Event Mail</h1>
      <%= form_with url: group_send_mail_path(@group), method: :get, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Content</label>
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "送信", class: 'btn btn-success'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
  <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"> <%= @title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= attachment_image_tag @group, :image, :fill, 40, 40, fallback: "no_image_icon.jpg" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
            <% @group.users.each do |member| %>
            <%= member.name %><br>
            <% end %>
            </td>
            <% if current_user.id == @group.owner_id %>
              <td><%= link_to "Edit", edit_group_path(@group), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Notice an Event", group_new_mail_path(@group), class: "btn btn-sm btn-info" %></td>
            <% elsif @group.users.include?(current_user) %>
              <td><%= link_to "Leave this group", group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% else %>
              <td><%= link_to "Join this group", group_join_path(@group), class: "btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>