config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "home/about" => 'homes#about'
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create, :destroy]
      get 'date_search', to: 'users#date_search'
  end

  get 'search' => 'searches#search'
  get 'category_search' => 'books#category_search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else @user = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.following_user
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.follower_user
    render 'show_follower'
  end

  def date_search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    create_at = params[:created_at]
    @date_search_book = @books.where('created_at LIKE ?', "#{create_at}%").count
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_date_search.html.erb
<h3>検索結果</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= date_search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/_index.html.erb
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image_icon.jpg" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>フォロー数:<%= user.following_user.count %></td>
            <td>フォロワー数:<%= user.follower_user.count %></td>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <td><%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %></td>
              <% else %>
                <td><%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %></td>
              <% end %>
            <% else %>
              <td colspan="1"></td>
            <% end %>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/date_search.js.erb
  $("#search_result").html("<%= j(render 'date_search', date_search_book: @date_search_book) %>");

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
      <label>Image</label>
      <%= f.attachment_field :profile_image, class: "form-control-file" %>
      </div>
      <div class="form-group">
      <label>Introduction</label>
      <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
      <%= f.submit "Update User", class: 'btn btn-secondary'%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
      <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
      <h2>Users</h2>
          <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>

      <%= form_with url: user_date_search_path(@user), method: :get do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: 'btn btn-primary' %>
      <% end %>

      <div id="search_result">
        <% if @date_search_book.present? %>
          <%= render 'date_search', date_search_book: @date_search_book %>
        <% end %>
      </div>
      <h3>投稿数の前日比・前週比</h3>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @today_book.count %>
            </td>
            <td>
              <%= @yesterday_book.count %>
            </td>
            <td>
              <% if @yesterday_book.count == 0 %>
                前日が０のため計算できません
              <% else %>
                <%= (@today_book.count / @yesterday_book.count.to_f * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @this_week_book.count %>
            </td>
            <td>
              <%= @last_week_book.count %>
            </td>
            <td>
              <% if @last_week_book.count == 0 %>
                前週が０のため計算できません
              <% else %>
                <%= (@this_week_book.count / @last_week_book.count.to_f * 100).round %>%
              <% end %>
            </td>
      </table>
      <h3>7日間分の投稿数</h3>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>６日前</th>
            <th>５日前</th>
            <th>４日前</th>
            <th>３日前</th>
            <th>２日前</th>
            <th>１日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @books.created_6day_ago.count %></td>
            <td><%= @books.created_5day_ago.count %></td>
            <td><%= @books.created_4day_ago.count %></td>
            <td><%= @books.created_3day_ago.count %></td>
            <td><%= @books.created_2day_ago.count %></td>
            <td><%= @books.created_yesterday.count %></td>
            <td><%= @books.created_today.count %></td>
      </table>
      <canvas id="myLineChart"></canvas>
      <script>
        $(document).on('turbolinks:load', function () {
          var ctx = document.getElementById("myLineChart");
            var myLineChart = new Chart(ctx, {
              type: 'line',
              data: {
                labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
                datasets: [
                  {
                  label: '投稿した本の数',
                  data: [<%= @books.created_6day_ago.count %>, <%= @books.created_5day_ago.count %>, <%= @books.created_4day_ago.count %>, <%= @books.created_3day_ago.count %>, <%= @books.created_2day_ago.count %>, <%= @books.created_yesterday.count %>, <%= @books.created_today.count %>],
                  borderColor: "rgba(0,0,255,1)",
                  backgroundColor: "rgba(0,0,0,0)"
                  }
                ],
              },
              options: {
                title: {
                  display: true,
                  text: '７日間の投稿数の比較'
                },
                scales: {
                  yAxes: [{
                    ticks: {
                      suggestedMax: 10,
                      suggestedMin: 0,
                      stepSize: 1,
                      callback: function(value, index, values){
                      return  value
                       }
                    }
                  }]
                },
              }
            });
          });
      </script>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
    <h2>Follow Users</h2>
    <% if @users.empty? %>
      <p>ユーザーはいません</p>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image_icon.jpg" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              フォロー数:<%= user.following_user.count %>
            </td>
            <td>
              フォロワー数:<%= user.follower_user.count %>
            </td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

app/views/users/show_follower.html.erb
    <h2>Follower Users</h2>
    <% if @users.empty? %>
      <p>ユーザーはいません</p>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image_icon.jpg" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              フォロー数:<%= user.following_user.count %>
            </td>
            <td>
              フォロワー数:<%= user.follower_user.count %>
            </td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>