config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "home/about" => 'homes#about'
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create, :destroy]
      get 'date_search', to: 'users#date_search'
  end

  get 'search' => 'searches#search'
  get 'category_search' => 'books#category_search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else @book = Book.all
    end
  end

  def self.category_search(search_word)
    @book = Book.where("category LIKE?","#{search_word}")
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 13.day.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else @user = User.all
    end
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all.order(params[:sort])
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:motice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def category_search
    @book = Book.new
    @user = current_user
    @books = Book.category_search(params[:keyword])
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

    before_action :follow_each_other, only: [:show]

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
      @chats = @room.chats
      @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def follow_each_other
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
     <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image_icon.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td><%= link_to book.category, category_search_path(keyword: book.category) %></td>
            <td id="favorite-btn_<%= book.id %>">
            <%= render 'favorites/favorite-btn', book: book %>
            </td>
            <td>コメント数:<%= book.book_comments.count %></td>
            <td>
            <div id="star-rate-<%= book.id %>"></div>
            <script>
              $('#star-rate-<%= book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= book.rate %>,
              });
            </script>
            </td>
            <td>閲覧数:<%= book.view_counts.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

app/views/books/_side.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follow</th>
            <th><%= link_to @user.following_user.count, following_user_path(@user) %></th>
          </tr>
          <tr>
            <th>follower</th>
            <th><%= link_to @user.follower_user.count, followers_user_path(@user) %></th>
          </tr>
        </tbody>
      </table>
      <% if @user != current_user %>
        <div id="follow_form">
        <% if current_user.following?(@user) %>
          <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: 'btn btn-info' %>
            <% if @user.following?(current_user) %>
            <%= link_to "chatを始める", chat_path(@user.id) %>
            <% end %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :POST, class: 'btn btn-success' %>
        <% end %>
        </div>
      <% else %>
        <div class="row">
          <%= link_to "", edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
        </div>
      <% end %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new, local:true do |f| %>
      <div class="form-group">
      <label>Title</label>
      <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
      <label>Opinion</label>
      <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
      <label>Category</label>
      <%= f.text_field :category, class: "form-control" %>
      </div>
      <div class="form-group" id="star">
        <%= f.label :rate %>
        <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
      </div>
      <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'book[rate]',
          half: true,
        });
       </script>

      <div class="form-group">
      <%= f.submit "Create Book", class: 'btn btn-success'%>
      </div>
      <% end %>
    </div>

app/views/books/category_search.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', obj: @book %>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label>Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Category</label>
        <%= f.text_field :category, class: "form-control" %>
      </div>
      <div class="form-group">
        <div id="star-rate-<%= @book.id %>"></div>
        <script>
        $('#star-rate-<%=@book.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @book.rate %>,
        });
        </script>
      </div>
      <div class="form-group">
      <%= f.submit "Update Book", class: 'btn btn-success'%>
      </div>
      <% end %>
      <%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> | <%= link_to "評価の高い順", books_path(sort: 'rate DESC') %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <%= render 'books/side', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image_icon.jpg" %></br><%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book) do %>
              <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td><%= @book.category %></td>
            <td id="favorite-btn_<%= @book.id %>">
            <%= render 'favorites/favorite-btn', book: @book %>
            </td>
            <td>
              コメント数:<%= @book.book_comments.count %>
            </td>
            <td>
            <div id="star-rate-<%= @book.id %>"></div>
            <script>
              $('#star-rate-<%= @book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.rate %>,
              });
            </script>
            </td>
            <td>
              閲覧数:<%= @book.view_counts.count %>
            </td>
            <% if @user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
        <div id = "comments_area">
        <%= render 'book_comments/index', book_comments: @book_comments %>
        </div>
        <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<h1><%= @user.name %>さんとのチャット</h1>
<div class="message" style="width: 400px;">
<% @chats.each do |chat| %>
  <% if chat.user_id == current_user.id %>
  <p style="text-align: right;"><%= chat.message %></p>
  <% else %>
  <p style="text-align: left;"><%= chat.message %></p>
  <% end %>
<% end %>
</div>

<%= form_with model: @chat do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
  <% f.submit %>
<% end %>